package com.ruleengine.hysc.fact;

/**
 * This class was automatically generated by the data modeler tool.
 * @author dalididilo
 */

public class AlarmBean implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("传感器类型")
    private java.lang.String type;
    @org.kie.api.definition.type.Label("报警等级")
    private java.lang.String grade;
    @org.kie.api.definition.type.Label("上限值")
    private double up;
    @org.kie.api.definition.type.Label("下限值")
    private double lower;
    @org.kie.api.definition.type.Label("通道")
    private java.lang.String tunnel;
    @org.kie.api.definition.type.Label("通道段")
    private java.lang.String tunnelStation;
    @org.kie.api.definition.type.Label("分区")
    private java.lang.String position;
    @org.kie.api.definition.type.Label("装置")
    private java.lang.String device;

    @org.kie.api.definition.type.Label("监测类型")
    private java.lang.String watchType;

    public AlarmBean() {
    }

    public java.lang.String getType() {
        return this.type;
    }

    public void setType(java.lang.String type) {
        this.type = type;
    }

    public java.lang.String getGrade() {
        return this.grade;
    }

    public void setGrade(java.lang.String grade) {
        this.grade = grade;
    }

    public double getUp() {
        return this.up;
    }

    public void setUp(double up) {
        this.up = up;
    }

    public double getLower() {
        return this.lower;
    }

    public void setLower(double lower) {
        this.lower = lower;
    }

    public java.lang.String getTunnel() {
        return this.tunnel;
    }

    public void setTunnel(java.lang.String tunnel) {
        this.tunnel = tunnel;
    }

    public java.lang.String getTunnelStation() {
        return this.tunnelStation;
    }

    public void setTunnelStation(java.lang.String tunnelStation) {
        this.tunnelStation = tunnelStation;
    }

    public java.lang.String getPosition() {
        return this.position;
    }

    public void setPosition(java.lang.String position) {
        this.position = position;
    }

    public java.lang.String getDevice() {
        return this.device;
    }

    public void setDevice(java.lang.String device) {
        this.device = device;
    }

    public java.lang.String getWatchType() {
        return this.watchType;
    }

    public void setWatchType(java.lang.String watchType) {
        this.watchType = watchType;
    }

    public AlarmBean(java.lang.String type, java.lang.String grade, double up,
                     double lower, java.lang.String tunnel,
                     java.lang.String tunnelStation, java.lang.String position,
                     java.lang.String device, java.lang.String watchType) {
        this.type = type;
        this.grade = grade;
        this.up = up;
        this.lower = lower;
        this.tunnel = tunnel;
        this.tunnelStation = tunnelStation;
        this.position = position;
        this.device = device;
        this.watchType = watchType;
    }

}