package com.puyuan.iotmanager.fact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Address implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "省 ")
    private java.lang.String province;
    @org.kie.api.definition.type.Label(value = "市")
    private java.lang.String city;
    @org.kie.api.definition.type.Label(value = "区")
    private java.lang.String distract;
    @org.kie.api.definition.type.Label(value = "详细")
    private java.lang.String detail;

    public Address() {
    }

    public java.lang.String getProvince() {
        return this.province;
    }

    public void setProvince(java.lang.String province) {
        this.province = province;
    }

    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }

    public java.lang.String getDistract() {
        return this.distract;
    }

    public void setDistract(java.lang.String distract) {
        this.distract = distract;
    }

    public java.lang.String getDetail() {
        return this.detail;
    }

    public void setDetail(java.lang.String detail) {
        this.detail = detail;
    }

    public Address(java.lang.String province, java.lang.String city,
                   java.lang.String distract, java.lang.String detail) {
        this.province = province;
        this.city = city;
        this.distract = distract;
        this.detail = detail;
    }

}