package com.puyuan.iotmanager.fact;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApplyInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "姓名")
    private java.lang.String name;
    @org.kie.api.definition.type.Label(value = "家庭住址")
    private com.puyuan.iotmanager.fact.Address familyAddress;
    @org.kie.api.definition.type.Label(value = "年龄")
    private java.lang.Integer age;

    public ApplyInfo() {
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public com.puyuan.iotmanager.fact.Address getFamilyAddress() {
        return this.familyAddress;
    }

    public void setFamilyAddress(
            com.puyuan.iotmanager.fact.Address familyAddress) {
        this.familyAddress = familyAddress;
    }

    public java.lang.Integer getAge() {
        return this.age;
    }

    public void setAge(java.lang.Integer age) {
        this.age = age;
    }

    public ApplyInfo(java.lang.String name,
                     com.puyuan.iotmanager.fact.Address familyAddress,
                     java.lang.Integer age) {
        this.name = name;
        this.familyAddress = familyAddress;
        this.age = age;
    }

}